[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:caddy]
command=caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:webhook]
command=python3 /opt/webhook/webhook-receiver.py
autorestart=true
environment=WEBHOOK_TOKEN="%(ENV_WEBHOOK_TOKEN)s",WEBHOOK_PORT="9000"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
